### ISSUE TITLE
Checkpoint throws ArithmeticException under certain clock conditions

### ISSUE THREAD

**Issue by akara** [svezfaz/akka-stream-checkpoint#6]
This seems to be due to clock granularity giving the same nanoTime for two pushes/pulls.

**Comment by svezfaz** [comment]
Hey @akara thanks for this!
Is this a condition you've noticed by using a bespoke `Clock` implementation, or did this happen using `System.nanoTime`?
My assumption was that in real life this would never happen, so using a neutral stat like 50% seems like a sensible choice.
