### ISSUE TITLE
Dropwizard backend - Use Hdrhistogram metrics reservoir for latency histograms

### ISSUE THREAD

**Issue by kmatasflp** [svezfaz/akka-stream-checkpoint#8]
One should use https://bitbucket.org/marshallpierce/hdrhistogram-metrics-reservoir for latency histograms when using Dropwizard (more precisely `HdrHistogramResetOnSnapshotReservoir` as most reporters take a snapshot every x seconds and send off statistics from that measuring window that was x seconds long and you do not want data to leak in from the previous reporting window ). See http://hdrhistogram.org/ for why you want HdrHistogram as the underlying data structure, or watch https://www.infoq.com/presentations/latency-pitfalls.

Kamon histograms are already powered by HdrHistogram, so it be nice if Dropwizard metrics behaved the same way

**Comment by svezfaz** [comment]
Thanks a lot for the feedback and for the resources @kmatasflp. Dropwizard backend is now based on HdrHistograms!
